### PR TITLE
an article about Ludwig van Beethoven Violin Sonatas

### PR DESCRIPTION
**Pull request by nadjmaakhal**

### CODE REVIEW

**Comment by claudiodsf** [comment]
Hello, I cannot merge this one since you made the modifications on your `main` branch, instead of your feature branch called `nadjma`. Maybe you can try swapping the names of these two branches?

**Comment by nadjmaakhal** [comment]
Hello sir, 
I switched the names of the two branches as you suggested.

**Comment by claudiodsf** [comment]
Hello, I cannot see it from GitHub. Maybe you have to do a `git push --force` on your computer?

**Comment by nadjmaakhal** [comment]
When I did **git push --force**, I received:

git push --force
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:nadjma

To push to the branch of the same name on the remote, use

    git push origin HEAD

so i did the first one : git push origin HEAD:nadjma

**Comment by claudiodsf** [comment]
Try the following:

- Move to the new `nadjma` branch (the old `main`): `git checkout nadjma`
- `git push --force --set-upstream origin nadjma`

Then you can do the same for the new `main` branch (the old `nadjma`):

- `git checkout main`
- `git push --force --set-upstream origin main`

**Comment by claudiodsf** [comment]
Looks like the swap worked on GitHub. You have now to redo the pull request from the `nadjma` branch 😉

**Pull request closed without merging**
